# Generated by Django 5.1.6 on 2025-02-12 09:23

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_cropping',
            field=image_cropping.fields.ImageRatioField('profile_picture', '430x430', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='profile picture cropping'),
        ),
    ]
